name = "Sonums"
uuid = "df126d66-b6ac-11e9-1558-59a14e4bac76"
authors = ["Milan Kloewer"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "^1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SoftPosit = "0775deef-a35f-56d7-82da-cfc52f91364d"

[targets]
test = ["Test","SoftPosit"]
